<a href="https://colab.research.google.com/github/Nokyep/DeepLearningClass_Practice/blob/master/CodePractice_2ndweek.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
3.14 * 10 * 10

314.0

In [3]:
3.14 * 10**2

314.0

In [4]:
type(10)

int

In [5]:
type(3.14)

float

In [6]:
type('python')

str

In [7]:
type([1,2,3])

list

In [8]:
type({1,2,3})

set

In [9]:
type((1,2,3))

tuple

In [10]:
r = 20
PI = 3.14 #원주율
area = PI * r**2 #반지름의 제곱

area

1256.0

#리스트 복습

In [11]:
lst = [10, 20, 30, 40, 50]

lst

[10, 20, 30, 40, 50]

In [12]:
lst[2]

30

In [13]:
lst[2] = 77

lst

[10, 20, 77, 40, 50]

In [14]:
len(lst)

5

# 리스트 슬라이싱

In [16]:
lst

[10, 20, 77, 40, 50]

In [17]:
lst[0:3] #0번 인덱스부터 순서대로 3개 출력

[10, 20, 77]

In [18]:
lst[2:] #두번째원소부터 끝까지 출력 (공백)

[77, 40, 50]

In [19]:
lst[:-1] #끝에서 하나 뺀 후 출력 = -1 바로 앞에것까지 출력 = 50 제외

[10, 20, 77, 40]

#  딕셔너리 - 키와 값이 쌍으로 이루어짐

In [20]:
car = {'HP' : 200, 'maker':"BMW"} #딕셔너리 정의

In [21]:
car['HP']

200

In [22]:
car['color'] = 'white' #새로운 원소 추가

In [23]:
car

{'HP': 200, 'color': 'white', 'maker': 'BMW'}

# if-else 문

In [24]:
temp = -10

In [26]:
if temp < 0 :
  print("영하 기온입니다.")
else :
  print("영상 기온입니다.")

영하 기온입니다.


# for 문

In [27]:
for i in [1,2,3,4,5]:
  print(i, end=" ") #print문의 끝은 enter이므로 enter가 아닌 한 칸 띄우기 실행명령어

1 2 3 4 5 

In [28]:
for i in [1,2,3,4,5]:
  print(i)

1
2
3
4
5


# function 함수 복습

In [29]:
def hellopython(): #함수 정의 (def)
  print("Hello Python!!")

In [30]:
hellopython()

Hello Python!!


In [36]:
def helloname(name): #helloname에서 name을 입력받음
  print("Hello " + name)

In [37]:
helloname("Deep Learning!!") #Hello 와 합쳐진 문자열이 출력됨

Hello Deep Learning!!


# 파이썬 클래스

In [40]:
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age
  
  def sayName(self):
    print("Hello My Name is " + self.name)

In [41]:
p1 = Person("James", 12)

In [42]:
p1.sayName()

Hello My Name is James


# 넘파이

In [43]:
import numpy as np #넘파이 모듈 사용 선언

In [44]:
a = np.array([1,2,3])

In [45]:
a

array([1, 2, 3])

In [46]:
a[0]

1

In [47]:
a[2]

3

# 2차원 배열 with numpy

In [48]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]]) #첫번째 인덱스 라인 (세로) / 두번째 인덱스 라인(가로)
                                          # b[0][2]인 경우 3을 가리키는 것임
                                          

In [49]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
b[2][2]

9

In [51]:
b[2][1]

8

In [52]:
b[2,1] #이렇게도 위와같이 출력 가능

8

# 딥러닝에서 매우 중요한 함수

In [53]:
np.zeros((3,4)) # 3,4 행렬 (0값만 가진 = zeros)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
np.ones((3,4)) # 3,4행렬 (1값만 가진 = ones)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
np.eye(3) #정방행렬이 만들어지며 대각성분이 지정이 된다.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
np.random.random((3,4)) #3,4행렬에 랜덤한 값 주어짐 0~1까지

array([[0.36766011, 0.80665722, 0.69253987, 0.0733223 ],
       [0.94494706, 0.03833435, 0.2271985 , 0.65000975],
       [0.76416132, 0.43585197, 0.97151518, 0.55095441]])

In [57]:
np.arange(5) #5개의 원소를 출력 = 인덱스 0부터하면 5는 제외될 수밖에 없음
              #np.arange(start,stop,step) = 시작값, 종료값, 간격값 
              # 매우 중요한 함수

array([0, 1, 2, 3, 4])

In [58]:
np.arange(2,100) #2부터시작해서 100 전까지

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
       70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [59]:
np.arange(1,101,2) #1에서 101까지 출력을 하지만 2씩 건너뛰며 출력 = 홀수 출력

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [61]:
np.linspace(0,10,100) #0에서 10까지인 것을 100개로 분할
                      #linear Space
                      #np.linspace(start,stop,num) = 시작값, 종료값, 개수
                      #종료값을 포함한다는 특징이 있음 (인덱스 값이 아니기때문이다.)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [62]:
np.linspace(0,99,100)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [63]:
import numpy as np
a = np.array([[0,1,2],[3,4,5],[6,7,8]])

a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [64]:
a.shape

(3, 3)

In [65]:
a.ndim

2

In [66]:
a.dtype

dtype('int64')

In [67]:
a.itemsize

8

In [68]:
a.size

9

# 배열 간의 연산

In [69]:
arr1 = np.array([[1,2],[3,4],[5,6]])
arr2 = np.array([[1,1],[1,1], [1,1]])

result = arr1 + arr2
result

array([[2, 3],
       [4, 5],
       [6, 7]])

# 브로드캐스팅

In [70]:
miles = np.array([1,2,3])
result = miles * 1.6
result

array([1.6, 3.2, 4.8])

In [71]:
arr1 = np.array([[1,2],[3,4], [5,6]])
arr2 = np.array([[2,2],[2,2], [2,2]])

result = arr1 * arr2
result

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [72]:
#행렬 곱셈

arr1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2 = np.array([[2,2], [2,2], [2,2]])

result = arr1 @ arr2

In [73]:
result

array([[12, 12],
       [30, 30],
       [48, 48]])

In [75]:
# numpy 배열에 함수 적용 예제

A = np.array([0,1,2,3])
10 * np.sin(A) #sin() 함수 적용

array([0.        , 8.41470985, 9.09297427, 1.41120008])

In [76]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a.sum() #a요소들의 합

45

In [77]:
a.min()

1

In [78]:
a.max()

9

In [79]:
scores = np.array([[99,93,60], [98,82,93], [93,65,81], [78,82,81]])

scores.mean(axis=0) #axis=0은 열을 의미한다.
                    # 열에서의 평균을 구한다.
                  

array([92.  , 80.5 , 78.75])

# 인덱싱과 슬라이싱

In [80]:
grades = np.array([88,72,93,94])

grades[1:3]

array([72, 93])

In [82]:
grades[:2]

array([88, 72])

In [83]:
# 논리적인 인덱싱

ages = np.array([18,19,25,30,28])

grades = ages > 20
grades

array([False, False,  True,  True,  True])

In [84]:
ages[ ages > 20 ]

array([25, 30, 28])

In [85]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

a[0,2]

3

In [87]:
a[0,0] = 12
a

array([[12,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [88]:
# 2차원 배열의 슬라이싱

a = np.array([[1,2,3], [4,5,6], [7,8,9]])

a[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [89]:
a[::2, ::2]

array([[1, 3],
       [7, 9]])

In [90]:
#reshape() 함수

# new_array = old_array.reshape((3,4))
#새로운 배열, 원래의배열, 배열의 차원 >의 순서

a = np.arange(12)




In [91]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [92]:
a.reshape(3,4) #본래 1차원배열인 a이지만 2차원으로 reshape()함수를 하면
                # 2차원배열로 바뀌어 출력

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
a.reshape(6, -1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [94]:
#균일 분포에서 난수 생성하기

np.random.seed(100)
np.random.rand(5)


array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [95]:
np.random.rand(5,3)

array([[0.12156912, 0.67074908, 0.82585276],
       [0.13670659, 0.57509333, 0.89132195],
       [0.20920212, 0.18532822, 0.10837689],
       [0.21969749, 0.97862378, 0.81168315],
       [0.17194101, 0.81622475, 0.27407375]])

In [96]:
#정규분포에서 난수 생성하기

np.random.randn(5)

array([ 0.67272081, -0.10441114, -0.53128038,  1.02973269, -0.43813562])

In [97]:
np.random.randn(5,4)

array([[-1.11831825,  1.61898166,  1.54160517, -0.25187914],
       [-0.84243574,  0.18451869,  0.9370822 ,  0.73100034],
       [ 1.36155613, -0.32623806,  0.05567601,  0.22239961],
       [-1.443217  , -0.75635231,  0.81645401,  0.75044476],
       [-0.45594693,  1.18962227, -1.69061683, -1.35639905]])

In [98]:
m, sigma = 10,2

In [99]:
m + sigma * np.random.randn(5)

array([ 7.53513097,  8.91112168,  8.66365653, 10.01462913,  8.77412253])

In [100]:
mu, sigma = 0, 0.1 #평균과 표준편차를 의미

np.random.normal(mu,sigma, 5)

# ex) a = np.random.normal(loc=0.0, scale=1.0, size=None) 
# 순서대로 loc = 평균 / scale = 표준편차 / size = 배열의 차원

array([ 0.12997481, -0.17330956, -0.09833101,  0.03575078, -0.16135785])

In [101]:
# 전치행렬 계산하기

import numpy as np

arr = np.array([[1,2],[3,4],[5,6]])

print(arr.T)

[[1 3 5]
 [2 4 6]]


In [102]:
print(arr)

[[1 2]
 [3 4]
 [5 6]]
